language: ruby
rvm:
- 2.0.0
deploy:
  provider: heroku
  api_key:
    secure: 2p+KQ8tqQM+Xri++Ztn7kysmOnc4zyZEGOdY53YscTVQ3pKFI9XaOFnOWNtyBOtfxv3buT1Zv79yF92/euRSvpbXUUaAfERBocNAZSxhdFPmipn09DNRGllN5QdEgXyylhkmK2PmLZqgUET7l416ROg/vZmHr/1b/8aF/rsfpPy3M0+3tuD0Rk3TGBsuroUUjaR6SM81Abxl02G1+QgUWMOX6Youm7ErxH3gnXPvdmapEGN9ltc/OPN1TxKJK7b7VzXAbJ8w+v9GeiCWipO4GpPsbOJPur5DQoqbsJpEzOKu/CDz/e2mrQ5v68y5LVYJZrL38OAPIH81YJYNRbgAvQvpPQCmYzZKEV2eBKLOS3KYb6McPb7MEzLEvg7ILuDYrFFCmYblYgGQp/qjjiqoP1UZXpdrOLchGUGumuOlCBGxfIFslwQIXkqKl9n1ZYsBU5yEhcKMD53NEm5LU6ns9wFhtk0lrSmbHMR8pTDkQVrRp4LIOR9pQ8J5XNqiNqijI9SXpWOimfO1ajisL+ckiRFvjPgOC5QvvhVAvDXge+X4lT9S5EG2yM83IlgpN7torpZWuv8f6+3A4kb74j3b2FbEJfUgt/R3L/G36p/i5vxfjZSGoTqMrYTh0+XKincXPABIrmHkHHkX7Ov7014iy+6xBjgbtQ/OUnVyQrmXxSA=
  app: morning-hamlet-77829
  on:
    repo: wnansseu/projet_LPA2
